Automatically re-run compilation script if it failed with Cannot Connect error.

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,3 +1,13 @@
 #!/bin/sh
 echo Compiling...
-/Applications/scala-2.8.1/bin/fsc -deprecation -encoding utf-8 -dependencyfile build/scala_dependencies -d build/classes -make:transitivenocp -classpath build/classes:lib/junit-4.9.jar src/main/scala/*.scala
+COMMAND="/Applications/scala-2.8.1/bin/fsc -deprecation -encoding utf-8 -dependencyfile build/scala_dependencies -d build/classes -make:transitivenocp -classpath build/classes:lib/junit-4.9.jar src/main/scala/*.scala"
+$COMMAND 2>stderr
+ERROR=$?
+STDERR=`cat stderr`
+if [ "$STDERR" == "Could not connect to compilation daemon." ]; then
+  echo "Rerunning because of 'could not connect' message"
+  $COMMAND
+  ERROR=$?
+fi
+rm -f stderr
+exit $ERROR
